### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by mikeal** [ipfs-inactive/RFC#8]
There hasn't been any activity in about a year and there's some confusion as to the difference between this repo and the `specs` repo.

It's also not clear where in the planning (roadmap, OKR, Project WG, etc) these RFC's are a factor or how they are integrated into any of the other IPFS processes.

**Comment by momack2** [comment]
also confused. let's archive it so the PRs don't disappear?

**Comment by ericronne** [comment]
@momack2 are you authorized to do the honors? (I'm not, sigh 😞)

**Comment by momack2** [comment]
will try!
